account/urls.py
from django.urls import path

from .views import *


app_name = 'account'

urlpatterns = [
    path('account/', index, name='index'),
]

api_app/urls.py
"""
В этом модуле представлены пути для отображения API.
"""

from django.urls import path, include

from rest_framework.routers import DefaultRouter
from .views import *


router = DefaultRouter()
router.register(r'data', DataViewSet)

app_name = 'api_app'

urlpatterns = [
    path('api/v1/', include(router.urls), name='my_api'),
]

db_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    # подключение документации админки.
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    # подключение приложения account.
    path('', include('files.urls')),
    # подключение приложения files.
    path('', include('registration.urls')),
    # подключение приложения registration.
    path('', include('api_app.urls')),
    # подключение приложения api_app.
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # подключение схемы документации.
    path('api/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    # подключение swagger.
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    # подключение redoc.
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files/urls.py
"""
В этом модуле представлены пути для приложения files.
"""

from django.urls import path
from .views import *

app_name = 'files'

urlpatterns = [
    path('upload/', uploads, name='file_upload'),
    path('files/', file_list, name='file_list'),
    path('file/<int:pk>/', file_view, name='file_details'),

]

registration/urls.py
"""
В этом модуле представлены пути для авторизации пользователя приложения.
"""

from django.urls import path
from django.contrib.auth.views import LoginView

from .views import *

app_name = 'registration'

urlpatterns = [
    path('signup/', registration, name='registration'),
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', logout_user, name='logout'),
    path('', welcome, name='welcome'),
]

account/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver


class Profile(models.Model):
    """
    Модель Profile представляет собой профиль пользователя.

    Который сохраняется при регистрации.
    """
    GENDER_CHOICE = (
        ("M", "М"),
        ("F", "Ж"),
        (None, "-")
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField('Аватар', blank=True, upload_to='avatar/', default='avatar/standard.jpg')
    gender = models.CharField(
        'Пол', max_length=1,
        choices=GENDER_CHOICE,
        blank=True
        )
    city = models.CharField('Город', max_length=100, blank=True)
    birth_date = models.DateField('Дата рождения', null=True, blank=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

api_app/models.py
from django.db import models

# Create your models here.

files/models.py
"""
В этом модуле представлены поля которые записываются в Базу данных.
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UploadsFileModel(models.Model):
    """
    Модель UploadsFileModel представляет собой данные.

    Которые можно сохранить в Базе Данных.
    """
    title = models.CharField('Название файла', max_length=200)
    description = models.TextField('Описание', null=True, blank=True)
    file = models.FileField('Файл', upload_to='uploads/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

account/forms.py
from django.forms import ModelForm

from .models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = 'avatar', 'gender', 'city', 'birth_date'

files/forms.py
from django import forms
from .models import UploadsFileModel


class UploadsFileForms(forms.ModelForm):
    class Meta:
        model = UploadsFileModel
        fields = ('title', 'file', 'description')

account/views.py
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.

def index(request):
    """Метод представляет личный кабинет пользователя."""
    username = request.user
    user = User.objects.get(username=username)
    context = {
        'user': user,
    }
    return render(request, 'account/index.html', context)

api_app/views.py
"""
В этом модуле лежит set представление.
"""

from django.shortcuts import render
from rest_framework import generics, viewsets
from files.models import UploadsFileModel
from .serializers import DataSerializers


class DataViewSet(viewsets.ModelViewSet):
    """
    Набор представлений для действий над файлами.

    Полный CRUD для сущностей файлов.
    """
    queryset = UploadsFileModel.objects.all()
    serializer_class = DataSerializers

files/views.py
"""
В этом модуле представлены представления загрузки файлов.

И отображение загружаемых файлов.
"""

from django.shortcuts import render, redirect, get_object_or_404
from .models import UploadsFileModel
from .forms import UploadsFileForms


# Create your views here.

def handle_uploaded_file(f):
    with open(f"media/uploads/{f.name}", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def uploads(request):
    """Метод обрабатывает запрос загрузки файла от пользователя."""
    if request.method == 'POST':
        form = UploadsFileForms(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(form.cleaned_data['file'])
            newfile = form.save(commit=False)
            newfile.user = request.user
            newfile.save()
            return redirect('files:file_list')
    else:
        form = UploadsFileForms()
    return render(request, 'files/my_files.html', {'form': form})


def file_list(request):
    """Метод представляет список загруженных файлов."""
    files = UploadsFileModel.objects.filter(user=request.user)
    context = {
        'files': files,
    }
    return render(request, 'files/list_files.html', context)


def file_view(request, pk):
    """Метод представляет информацию о файле."""
    file = get_object_or_404(UploadsFileModel, pk=pk, user=request.user)
    if request.method == 'GET':
        form = UploadsFileForms(instance=file)
        context = {
            'file': file,
            'form': form,
        }
        return render(request, 'files/detail_files.html', context)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{% static 'image/db.ico'%}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>
    {% block title %}

    {% endblock %}
  </title>
    

</head>

<body>
<header>

    <div class="header__container">
        {% if user.is_authenticated %}
            <p>Вы зашли под именем: {{ user.username }}</p>
            <a href="{% url 'account:index' %}">Главная</a>
            <form action="{% url 'registration:logout' %}"  method="post">
            {% csrf_token %}
            <button type="submit">Выйти</button>
        {% else %}
            <a href="{% url 'registration:login' %}">Войти</a>
            <a href="{% url 'registration:registration' %}">Зарегистрироваться</a>

        {% endif %}
        </form>
    </div>
</header>

{% block content %}

{% endblock %}
</body>
</html>

templates/files/detail_files.html
{% extends 'base.html' %}

{% block title %}
    {{ file.title }}
{% endblock %}

{% block content %}
<div class="container">
<h3>{{ file.title }}</h3>
  {% if file.description %}
    <h3>{{ file.description }}</h3>
  {% endif %}

  <div>
    <a href="{{ file.file.url }}" download="{{ file.file.url }}">Скачать Файл</a>
    <a href="{% url 'files:file_list' %}">К списку файлов</a>
  </div>

</div>
{% endblock %}

templates/files/list_files.html
{% extends 'base.html' %}

{% block title %}
   Files List
{% endblock %}

{% block content %}
<h1>Files</h1>
   <ul>
    {% for file in files %}
            <li>
              <a href="{% url 'files:file_details' pk=file.pk %}">
                <h3>{{ file.title }}</h3>
              </a>
            </li>


    {% endfor %}

</ul>
<a href="{% url 'files:file_upload' %}">Загрузить Файл</a>
{% endblock %}

templates/files/my_files.html
{% extends 'base.html' %}

{% block title %}
    Files
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <p><button type="submit">Отправить</button></p>
</form>
<a href="{% url 'files:file_list' %}">Мои Файлы</a>
{% endblock %}